### ISSUE TITLE
Space character between value and unit (rem)

### ISSUE THREAD

**Issue by rikwillems** [creaminternet/magento2-theme-blank-sass#11]
My css file contains a space character between the value and unit of a property, creating an invalid propery.
```
h1 {
  font-weight: 300;
  line-height: 1.1;
  font-size: 2.6 rem;
  margin-top: 0;
  margin-bottom: 2 rem;
}
```

Some investigation leads me to: https://github.com/creaminternet/magento2-theme-blank-sass/blob/master/styles/vendor/magento-ui/_utilities.scss#L28

If you replace this line with the following the space character is removed and everything is fine again.
```
                $_value: #{$_value * 1}#{$font-size-unit};
```

**Comment by edwinbos** [comment]
@rikwillems Thanks for your contribution. This is now fixed in the latest release: https://github.com/creaminternet/magento2-theme-blank-sass/releases/tag/1.6.3
